### ISSUE TITLE
Looks great! But what is it?

### ISSUE THREAD

**Issue by judgej** [insulin/cli#64]
A command-line tool for sweetening my tea, or for configuring a CRM?

A single paragraph at the top of README.md would really help to put people in the picture, and would help people find this repository when searching for sugar-related stuff. As it is, I saw it mentioned in passing in the FIG discussions, but still don't have the slightest clue what it is after visiting this repo.

**Comment by alias-mac** [comment]
Now we are releasing a command line as part of SugarCRM, we no longer need this project. Closing.
